project:
  type: website
  output-dir: _site

website:
  title: "Tomas Diviak"
  favicon: TDfavicon.ico
  search: false
  navbar:
    background: light
    foreground: dark
    title: "Tomas Diviak"
    left:
      - text: "About me"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Contact me"
        href: contact.qmd

format:
  html:
    theme: litera
    css: styles/site.css
    toc: false
