---
title: "Publications"
title-block-banner: false
---

::: {.references .links}
Vörös, A., & **Diviák, T.** (2025). Studying network change in education with stochastic actor-oriented models. In N. Kolleck (Ed.), *Handbook of Social Network Analysis and Education* (pp. 242-258). Edward Elgar Publishing.

**Diviák, T.**, & Lord, N. (2024). Connecting the corrupt: Data sources to study organisational and white-collar crime networks in the United Kingdom. In L. Huey & D. Buil-Gil (Eds.), *Crime Data Handbook*. Bristol University Press.

Lintner, T., **Diviák, T.**, Šeďová, K., & Obrovská, J. (2025). Revisiting Ukrainian refugees struggling to integrate into Czech school social networks. *Social Psychology of Education*, 28(1), 174. [https://doi.org/10.1007/s11218-025-10134-5](https://doi.org/10.1007/s11218-025-10134-5){.publ-link target="_blank"}

Topinková, R., & **Diviák, T.** (2025). It takes two to tango: A directed two-mode network approach to desirability on a mobile dating app. *PLoS ONE*, 20(7), e0327477. [https://doi.org/10.1371/journal.pone.0327477](https://doi.org/10.1371/journal.pone.0327477){.publ-link target="_blank"}

Van Deuren, S., **Diviák, T.**, & Blokland, A. (2025). Co-offending among outlaw motorcycle gang members: The role of social and geographical proximity. *Journal of Criminal Justice*, 96, 102340. [https://doi.org/10.1016/j.jcrimjus.2024.102340](https://doi.org/10.1016/j.jcrimjus.2024.102340){.publ-link target="_blank"}

**Diviák, T.**, & Lerner, J. (2025). Understanding the mechanisms that drive relational events dynamics in corruption networks. *Journal of Quantitative Criminology*. [https://doi.org/10.1007/s10940-025-09605-x](https://doi.org/10.1007/s10940-025-09605-x){.publ-link target="_blank"}

van Nassau, C. S., **Diviák, T.**, Weerman, F., & de Poot, C. (2024). Radical networks and terrorist action: The importance of social relationships and network positions. *Global Crime*. [https://doi.org/10.1080/17440572.2024.2437379](https://doi.org/10.1080/17440572.2024.2437379){.publ-link target="_blank"}

Lintner, T., **Diviák, T.**, & Nekardová, B. (2024). Interaction dynamics in classroom group work. *Social Networks*, 79, 14-24. [https://doi.org/10.1016/j.socnet.2024.05.002](https://doi.org/10.1016/j.socnet.2024.05.002){.publ-link target="_blank"}

Buil-Gil, D., Bui, L., Trajtenberg, N., **Diviák, T.**, Kim, E., & Solymosi, R. (2024). Diversifying crime datasets in introductory statistical courses in criminology. *Journal of Criminal Justice Education*, 1-27. [https://doi.org/10.1080/10511253.2024.2334706](https://doi.org/10.1080/10511253.2024.2334706){.publ-link target="_blank"}

Brom, C., **Diviák, T.**, Drbohlav, J., Korbel, V., Levínský, R., Neruda, R., Kadlecová, G., Šlerka, J., Šmíd, M., Trnka, J., & Vidnerová, P. (2023). Rotation-based schedules in elementary schools to prevent COVID-19 spread: A simulation study. *Scientific Reports*, 13(1), Article 1. [https://doi.org/10.1038/s41598-023-45788-8](https://doi.org/10.1038/s41598-023-45788-8){.publ-link target="_blank"}

Lintner, T., **Diviák, T.**, Nekardová, B., Lehotský L., & Vašečka M. (2023). Slovak MPs' response to the Russian invasion of Ukraine in light of conspiracy theories and the polarization of political discourse. *Humanities and Social Sciences Communications*, 10, 758. [https://doi.org/10.1057/s41599-023-02276-8](https://doi.org/10.1057/s41599-023-02276-8){.publ-link target="_blank"}

van Nassau, C. S., **Diviák, T.**, Weerman, F., & de Poot, C. (2023). Structure, positions and mechanisms: a case study of two Dutch Salafi-Jihadi networks. *European Journal of Criminology*. [https://doi.org/10.1177/14773708231207559](https://doi.org/10.1177/14773708231207559){.publ-link target="_blank"}

**Diviák, T.**, & Ocelík, P. (2023). Exponenciální modely náhodných grafů: modelování relačních mechanismů na případu sítě organizací zapojených v českém uhelném sektoru (transl.: Exponential random graph models: Modelling relational mechanisms in the Czech coal subsystem inter-organizational network). *Czech Sociological Review*. [https://doi.org/10.13060/csr.2023.046](https://doi.org/10.13060/csr.2023.046){.publ-link target="_blank"}

Lintner, T., **Diviák, T.**, Šeďová, K., & Hlaďo., P. (2023). Ukrainian refugees struggling to integrate into Czech school social networks. *Humanities and Social Sciences Communications*, 10, 409. [https://doi.org/10.1057/s41599-023-01880-y](https://doi.org/10.1057/s41599-023-01880-y){.publ-link target="_blank"}

**Diviák, T.**, Šlerka, J., Šmíd, M., & Zajíček, M. (Ed.). (2023). Rok s pandemií covid-19. *Karolinum.*

**Diviák, T.**, & Lord, N. (2023). From text to ties: Extraction of corruption network data from deferred prosecution agreements. *Data & Policy*, 5, e4. [https://doi.org/10.1017/dap.2022.41](https://doi.org/10.1017/dap.2022.41){.publ-link target="_blank"}

**Diviák, T.** (2023). Structural resilience and recovery of a criminal network after disruption: A simulation study. *Journal of Experimental Criminology*. [https://doi.org/10.1007/s11292-023-09563-z](https://doi.org/10.1007/s11292-023-09563-z){.publ-link target="_blank"}

Berec, L., **Diviák, T.**, Kuběna, A., Levínský, R., Neruda, R., Suchopárová, G., Šlerka, J., Šmíd, M., Trnka, J., Tuček, V., Vidnerová, P., & Zajíček, M. (2023). On the contact tracing for COVID-19: A simulation study. *Epidemics*, 100677. [https://doi.org/10.1016/j.epidem.2023.100677](https://doi.org/10.1016/j.epidem.2023.100677){.publ-link target="_blank"}

Pilnáček, M., Mazák, J., & **Diviák, T.** (2022). Polarizace v internetové diskuzi: Analýza sociálních sítí s negativními vazbami. In R. Hladík (Ed.), *Digitální obrat v českých humanitních vědách* (pp. 315-341). Karolinum.

Berec, L., Smyčka, J., Levínský, R., Hromádková, E., Šoltés, M., Šlerka, J., Tuček, V., Trnka, J., Šmíd, M., Zajíček, M., **Diviák, T.**, Neruda, R., & Vidnerová, P. (2022). Delays, Masks, the Elderly, and Schools: First Covid-19 Wave in the Czech Republic. *Bulletin of Mathematical Biology*, 84(8), 75. [https://doi.org/10.1007/s11538-022-01031-5](https://doi.org/10.1007/s11538-022-01031-5){.publ-link target="_blank"}

Ocelík, P., **Diviák, T.**, Lehotský, L., Svobodová, K., & Hendrychová, M. (2022). Facilitating the Czech Coal Phase-Out: What Drives Inter-Organizational Collaboration? *Society & Natural Resources*, 1-20. [https://doi.org/10.1080/08941920.2022.2065394](https://doi.org/10.1080/08941920.2022.2065394){.publ-link target="_blank"}

**Diviák, T.**, van Nassau, C. S., Dijkstra, J. K., & Snijders, T. A. B. (2022). Dynamics and disruption: Structural and individual changes in two Dutch Jihadi networks after police interventions. *Social Networks*, 70, 364-374. [https://doi.org/10.1016/j.socnet.2022.04.001](https://doi.org/10.1016/j.socnet.2022.04.001){.publ-link target="_blank"}

**Diviák, T.**, & Lord, N. (2022). Tainted ties: The structure and dynamics of corruption networks extracted from deferred prosecution agreements. *EPJ Data Science*, 11(1), 7. [https://doi.org/10.1140/epjds/s13688-022-00320-2](https://doi.org/10.1140/epjds/s13688-022-00320-2){.publ-link target="_blank"}

**Diviák, T.** (2021). Není hvězda jako hvězda: Identifikace klíčových aktérů v sociálních sítích. *Social Studies*, 18(1), 101-120. [https://doi.org/10.5817/SOC2021-1-101](https://doi.org/10.5817/SOC2021-1-101){.publ-link target="_blank"}

**Diviák, T.** (2021). Kriminální sítě: Aktéři, mechanismy a struktury. *Karolinum.*

Diviák, T., Dijkstra, J. K., van der Wijk, F., Oosting, I., & Wolters, G. (2021). Women trafficking networks: Structure and stages of women trafficking in five Dutch small-scale networks. *European Journal of Criminology*, 147737082110531. [https://doi.org/10.1177/14773708211053135](https://doi.org/10.1177/14773708211053135){.publ-link target="_blank"}

**Diviák, T.**, Coutinho, J. A., & Stivala, A. D. (2020). A Man's World? The Structural Positions of Men and Women in an Organized Criminal Network. *Crime, Law and Social Change*. [https://doi.org/10.1007/s10611-020-09910-5](https://doi.org/10.1007/s10611-020-09910-5){.publ-link target="_blank"}

Coutinho, J., **T. Diviák**, D. A. Bright, J. Koskinen. (2020). Multilevel determinants of collaboration between organised criminal groups. *Social Networks*. [https://doi.org/10.1016/j.socnet.2020.04.002](https://doi.org/10.1016/j.socnet.2020.04.002){.publ-link target="_blank"}

**Diviák, T.** (2019). Key aspects of covert networks data collection: Problems, challenges, and opportunities. *Social Networks*. [https://doi.org/10.1016/j.socnet.2019.10.002](https://doi.org/10.1016/j.socnet.2019.10.002){.publ-link target="_blank"}

**Diviák, T.**, Dijkstra, J. K., & Snijders, T. A. B. (2019). Poisonous connections: A case study on a Czech counterfeit alcohol distribution network. *Global Crime*, 1-23. [https://doi.org/10.1080/17440572.2019.1645653](https://doi.org/10.1080/17440572.2019.1645653){.publ-link target="_blank"}

Lipkova, H., **Diviák, T.**, Jarolimkova, A., Drobikova, B., & Landova, H. (2019). Assessing Libraries' Community Roles. Proof of Concept. In S. Kurbanoğlu, S. Špiranec, Y. Ünal, J. Boustany, M. L. Huotari, E. Grassian, ... L. Roy (Ed.), *Information Literacy in Everyday Life* (Roč. 989, s. 83-93). [https://doi.org/10.1007/978-3-030-13472-3_8](https://doi.org/10.1007/978-3-030-13472-3_8){.publ-link target="_blank"}

Mochtak, M., & **Diviák, T.** (2019). Looking Eastward: Network Analysis of Czech Deputies and Their Foreign Policy Groups. *Problems of Post-Communism*, 1-16. [https://doi.org/10.1080/10758216.2018.1561191](https://doi.org/10.1080/10758216.2018.1561191){.publ-link target="_blank"}

**Diviák, T.**, Dijkstra, J. K., & Snijders, T. A. B. (2018). Structure, multiplexity, and centrality in a corruption network: The Czech Rath affair. *Trends in Organized Crime*, 1-24. [https://doi.org/10.1007/s12117-018-9334-y](https://doi.org/10.1007/s12117-018-9334-y){.publ-link target="_blank"}

Mazák, J., & **Diviák, T**. (2018). Transactional activism without transactions: Network perspective on anti-corruption activism in the Czech Republic. *Social Movement Studies*, 17(2), 203-218. [https://doi.org/10.1080/14742837.2017.1404904](https://doi.org/10.1080/14742837.2017.1404904){.publ-link target="_blank"}

**Diviák, T.** (2018a). Pojetí aktéra a jednání v analytické sociologii. In J. Šubrt & M. Německý (Ed.), *Jedinec a společnost: Úvahy nad konceptem homo sociologicus* (s. 73-89). SLON - sociologické nakladatelství.

**Diviák, T.** (2018b). Sinister connections: How to analyse organised crime with social network analysis? *AUC PHILOSOPHICA ET HISTORICA*, 2018(2), 115-135. [https://doi.org/10.14712/24647055.2018.7](https://doi.org/10.14712/24647055.2018.7){.publ-link target="_blank"}

**Diviák, T.** (2017). Ekvivalence a blokové modelování v analýze sociálních sítí. *Naše Společnost*, *1*(15), 27. [https://doi.org/10.13060/1214438X.2017.1.15.366](https://doi.org/10.13060/1214438X.2017.1.15.366){.publ-link target="_blank"}
:::
