---
title: "Teaching"
title-block-banner: false
---

::: {.course}
## Regular courses

Crime and Networks

Introduction to Social Network Analysis

Data Analysis in R & RStudio (department of Criminology, University of Manchester)

Data Analysis in Sociology I. & II.; Social Network Models; Introduction to Analytical Sociology; Social Network Analysis (all department of Sociology, Charles University)

Advanced Research Methods (department of Social Work, Charles University)
:::

::: {.course}
## Guest teaching

Serious & Organized Crime (department of Criminology, University of Manchester)

Introduction to Sociology; Chapters in Social Deviance; Contemporary Societies (all department of Sociology, Charles University)
:::

::: {.course}
## Workshops

Introduction to Social Network Analysis (Prague Summer School of Quantitative Methods, 2019)

Introduction to Social Network Analysis (University of Luxembourg, 2018)

Introduction to Social Network Analysis (Czech Network for Social Network Analysis conferences)

Application of Social Network Analysis in Police Investigation (Ministry of Interior of the Czech Republic, 2017)
:::
